### ISSUE TITLE
Failed to load a library: cairo / cairo-2 / cairo-gobject-2

### ISSUE THREAD

**Issue by metalmolly** [typhoon-hil/allure-docx#18]
Running v0.3.2 of the standalone 32 bit executable built for windows fails. Seems to be the same issue as #13.
```
c:\>allure-docx.exe allure-results allure.docx
Template: C:\Users\Allure\AppData\Local\Temp\_MEI130242\template.docx
Traceback (most recent call last):
  File "allure_docx\commandline.py", line 69, in <module>
  File "lib\site-packages\click\core.py", line 764, in __call__
  File "lib\site-packages\click\core.py", line 717, in main
  File "lib\site-packages\click\core.py", line 956, in invoke
  File "lib\site-packages\click\core.py", line 555, in invoke
  File "allure_docx\commandline.py", line 46, in main
  File "allure_docx\process.py", line 304, in run
  File "allure_docx\piechart.py", line 43, in create_piechart
  File "lib\site-packages\pygal\graph\public.py", line 118, in render_to_png
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "D:\WORK\venv32alluredocx\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "lib\site-packages\cairosvg\__init__.py", line 41, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "D:\WORK\venv32alluredocx\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "lib\site-packages\cairosvg\surface.py", line 24, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "D:\WORK\venv32alluredocx\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "lib\site-packages\cairocffi\__init__.py", line 41, in <module>
  File "lib\site-packages\cairocffi\__init__.py", line 38, in dlopen
OSError: dlopen() failed to load a library: cairo / cairo-2 / cairo-gobject-2
[4424] Failed to execute script commandline
```
Running the same with v0.3.1 works fine
```
c:\>allure-docx.exe allure-results allure.docx
Template: C:\Users\Allure\AppData\Local\Temp\_MEI137922\template.docx
base.css
C:\Users\Allure\AppData\Local\Temp\_MEI137922\pygal\css\base.css
OPENED
style.css
C:\Users\Allure\AppData\Local\Temp\_MEI137922\pygal\css\style.css
OPENED
graph.css
C:\Users\Allure\AppData\Local\Temp\_MEI137922\pygal\css\graph.css
OPENED
```
Also file size for v0.3.2 is much smaller, 9.4MB versus 16MB for v0.3.1.

**Comment by Sup3rGeo** [comment]
Thanks for the report! I confirmed this bug, let you know when we have a fix.

**Comment by Sup3rGeo** [comment]
For the moment we have just withdrawn the v.0.3.2 release so users will just use the latest working version.
