### ISSUE TITLE
[36664] Failed to execute script commandline

### ISSUE THREAD

**Issue by ManuCosmo** [typhoon-hil/allure-docx#26]
allure-docx --pdf kite-allure-reports report.pdf
Template: C:\Users\manua\AppData\Local\Temp\_MEI416042\template.docx
Traceback (most recent call last):
  File "allure_docx\commandline.py", line 74, in <module>
  File "lib\site-packages\click\core.py", line 722, in __call__
  File "lib\site-packages\click\core.py", line 697, in main
  File "lib\site-packages\click\core.py", line 895, in invoke
  File "lib\site-packages\click\core.py", line 535, in invoke
  File "allure_docx\commandline.py", line 51, in main
  File "allure_docx\process.py", line 298, in run
  File "allure_docx\process.py", line 95, in build_data
KeyError: 'PASSED'
[36664] Failed to execute script commandline

**Comment by Sup3rGeo** [comment]
Thanks for the report! Would it be possible to provide the `allure-reports` folder you are using so we can reproduce it locally?

**Comment by ManuCosmo** [comment]
Hi, here you go:
[kite-allure-reports.zip](https://github.com/typhoon-hil/allure-docx/files/3749839/kite-allure-reports.zip)
