### ISSUE TITLE
Problems with attachments

### ISSUE THREAD

**Issue by mcpabst** [typhoon-hil/allure-docx#27]
After running
C:\Users\mpabst\Downloads>allure-docx.exe c:\Projekte\Destatis\git\general\template-under-test\target\allure-results\ c:\test\t.doc
`
Template: C:\Users\mpabst\AppData\Local\Temp\_MEI111682\template.docx
base.css
C:\Users\mpabst\AppData\Local\Temp\_MEI111682\pygal\css\base.css
OPENED
style.css
C:\Users\mpabst\AppData\Local\Temp\_MEI111682\pygal\css\style.css
OPENED
graph.css
C:\Users\mpabst\AppData\Local\Temp\_MEI111682\pygal\css\graph.css
OPENED
Traceback (most recent call last):
  File "allure_docx\commandline.py", line 74, in <module>
  File "lib\site-packages\click\core.py", line 722, in __call__
  File "lib\site-packages\click\core.py", line 697, in main
  File "lib\site-packages\click\core.py", line 895, in invoke
  File "lib\site-packages\click\core.py", line 535, in invoke
  File "allure_docx\commandline.py", line 51, in main
  File "allure_docx\process.py", line 306, in run
  File "allure_docx\process.py", line 279, in create_docx
  File "allure_docx\process.py", line 173, in print_attachments
KeyError: 'type'
[11248] Failed to execute script commandline
`

**Comment by jppercy** [comment]
I had this issue and the workaround was using --detail-level compact

The default, I think it's full...

So:

C:\projects\my_project>allure-docx.exe --detail-level compact reports results/test.docx

**Comment by mcpabst** [comment]
Thanks. This workaround works also for me.

**Comment by victorinho20** [comment]
Hello i have this issue too, but i don't understand the solution.

can you help me please? Thanks!

RegardsS
