### ISSUE TITLE
Compact works but full doesn't

### ISSUE THREAD

**Issue by JackQL1119** [typhoon-hil/allure-docx#33]
Allure 2.13.6
Allure-testng

`.\allure-docx.exe --detail-level full .\allure-results\ test1.docx`

```
OPENED
Traceback (most recent call last):
  File "allure_docx\commandline.py", line 74, in <module>
  File "lib\site-packages\click\core.py", line 722, in __call__
  File "lib\site-packages\click\core.py", line 697, in main
  File "lib\site-packages\click\core.py", line 895, in invoke
  File "lib\site-packages\click\core.py", line 535, in invoke
  File "allure_docx\commandline.py", line 51, in main
  File "allure_docx\process.py", line 306, in run
  File "allure_docx\process.py", line 280, in create_docx
  File "allure_docx\process.py", line 198, in print_steps
  File "allure_docx\process.py", line 197, in print_steps
  File "allure_docx\process.py", line 173, in print_attachments
KeyError: 'type'
[14024] Failed to execute script commandline
```

**Comment by JackQL1119** [comment]
full_onfail also generates the .docx

**Comment by AdActa89** [comment]
im having the same issue
is there any way to get attachments into to the report?
compact or full_onfail works but having the attachments in the report would be great :)
