### ISSUE TITLE
None Template 

### ISSUE THREAD

**Issue by Apte-m** [typhoon-hil/allure-docx#40]
allure-docx   /Users/artem/AquaProjects/is-pk-automation/build/allure-results/ result.pdf
Template: None

 allure-docx   generate /Users/artem/AquaProjects/is-pk-automation/build/allure-results --template default.docx
Template: /Users/artem/default.docx
Traceback (most recent call last):
  File "/opt/homebrew/bin/allure-docx", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/allure_docx/commandline.py", line 87, in main
    report_builder = ReportBuilder(allure_dir=allure_dir, config=report_config)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/allure_docx/report_builder.py", line 32, in __init__
    self.document = Document(config['template_path'])
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/docx/api.py", line 25, in Document
    document_part = Package.open(docx).main_document_part
                    ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/docx/opc/package.py", line 128, in open
    pkg_reader = PackageReader.from_file(pkg_file)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/docx/opc/pkgreader.py", line 32, in from_file
    phys_reader = PhysPkgReader(pkg_file)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/docx/opc/phys_pkg.py", line 30, in __new__
    raise PackageNotFoundError(
docx.opc.exceptions.PackageNotFoundError: Package not found at '/Users/artem/default.docx'
artem@MacBook-Air-Artem-2 ~ % allure-docx   generate /Users/artem/AquaProjects/is-pk-automation/build/allure-results                        
Template: None
Traceback (most recent call last):
  File "/opt/homebrew/bin/allure-docx", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/allure_docx/commandline.py", line 87, in main
    report_builder = ReportBuilder(allure_dir=allure_dir, config=report_config)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/allure_docx/report_builder.py", line 56, in __init__
    self._build_data()
  File "/opt/homebrew/lib/python3.11/site-packages/allure_docx/report_builder.py", line 124, in _build_data
    json_results = [f for f in listdir(allure_dir) if isfile(join(allure_dir, f)) and "result" in f]
                               ^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/artem/generate'
artem@MacBook-Air-Artem-2 ~ %

**Comment by bjarnesc** [comment]
There is no such command as `generate`. See `allure-docx --help` for usage. Make it `allure-docx --template default.docx /Users/artem/AquaProjects/is-pk-automation/build/allure-results PATH_TO_DOCX.docx` for example.
