### ISSUE TITLE
Not able to generate pdf report for selenium java maven testng framework

### ISSUE THREAD

**Issue by Sai7574** [typhoon-hil/allure-docx#44]
C:\Users\niranjan.pa\Downloads>allure-docx --pdf C:\WF\AllurereportingSeleniumTestNG\AllurereportingSeleniumTestNG\AllurereportingSeleniumTestNG\allure-results allure.docx
Template: C:\Users\niranjan.pa\AppData\Local\Temp\_MEI222082\template.docx
Traceback (most recent call last):
  File "allure_docx\commandline.py", line 74, in <module>
  File "lib\site-packages\click\core.py", line 722, in __call__
  File "lib\site-packages\click\core.py", line 697, in main
  File "lib\site-packages\click\core.py", line 895, in invoke
  File "lib\site-packages\click\core.py", line 535, in invoke
  File "allure_docx\commandline.py", line 51, in main
  File "allure_docx\process.py", line 300, in run
  File "allure_docx\process.py", line 95, in build_data
KeyError: 'status'
[16892] Failed to execute script commandline

can u help out me?
![Screenshot (7)](https://github.com/typhoon-hil/allure-docx/assets/113346566/05eccdff-3724-41a3-aae9-c78b7c6fd2f9)

**Comment by bjarnesc** [comment]
It seems some of your test results don't have a status (e.g. successful, failed), which seems rather odd. The library was only tested with java junit and python pytest, so this might have to do with TestNG, but I cannot be sure. If you could provide the json test rusult data I could look over it.

**Comment by Sai7574** [comment]
Hi thanks for letting me know iam sharing zip file of allure results. Plz
help out me thanks for your help

**Comment by bjarnesc** [comment]
Alright. I cannot see any shared files though.

**Comment by Sai7574** [comment]
Can u try now Im forwarding zip file can u check your gmail once

**Comment by Sai7574** [comment]
[allure-results.zip](https://github.com/typhoon-hil/allure-docx/files/12844546/allure-results.zip)

**Comment by bjarnesc** [comment]
It seems the "testCaseId" that is used is a parameter usually only used by allure test ops (see https://allurereport.org/docs/how-it-works/test-result-file/) and probably not mandatory. I exchanged it for "fullName", which should work. Please checkout and use https://github.com/bjarnesc/allure-docx/ while the merge request is being processed, as I do not have access rights for this repo.

Please give feedback if it does.

**Comment by Sai7574** [comment]
There is no latest version v0.4.1 can u help out where can I find?

**Comment by bjarnesc** [comment]
> There is no latest version v0.4.1 can u help out where can I find?

Simply install with pip from source 
```
pip install allure-docx@git+https://github.com/bjarnesc/allure-docx.git#egg=allure_docx-0.4.1
```

**Comment by Sai7574** [comment]
![image](https://github.com/typhoon-hil/allure-docx/assets/113346566/512d1fe1-953f-492f-969b-786a8595abcf)
[allure.docx](https://github.com/typhoon-hil/allure-docx/files/12905292/allure.docx)

PDF:
![image](https://github.com/typhoon-hil/allure-docx/assets/113346566/9a4c838a-627d-4c0c-95f6-98082b9b71fd)
![image](https://github.com/typhoon-hil/allure-docx/assets/113346566/160bc683-50d4-4174-af4a-051cc1f43415)
[allure.pdf](https://github.com/typhoon-hil/allure-docx/files/12905396/allure.pdf)


It is Generating in word Doc file and pdf format but pdf is not opening  and screenshots are not displaying in word Doc can u check from your end also I have forwarded for u allure results zip Plz check and let me know thanks for helping out me Appreciate u r effort. First one is Word Doc File and Second One is Pdf File

**Comment by bjarnesc** [comment]
This seems to be because your attachment files do not have a proper type ending. Rename them to .png files (and update the attachement path inside the tests obviously). Then it should work. 

This is a problem with Word as it does not seem to be able to process attachements without type ending.

**Comment by Sai7574** [comment]
When iam generating allure results in that screen shot has file type and it is not having .png format and .png format is not generating in allure-results folder can u help on it thanks

**Comment by bjarnesc** [comment]
> When iam generating allure results in that screen shot has file type and it is not having .png format and .png format is not generating in allure-results folder can u help on it thanks

I really tried but I cannot understand your sentence. Please try to use some grammar that makes sense.

**Comment by Sai7574** [comment]
I am generating allure results in that screenshot, but the file type is not.png, and the.png format is not creating in the allure-results folder. Could you please assist? Thank you.
